version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: crawl4ai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=crawl4ai
    networks:
      - crawl4ai-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/crawl4ai --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crawl4ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/crawl4ai
      - PORT=8000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - crawl4ai-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crawl4ai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - crawl4ai-network

networks:
  crawl4ai-network:
    driver: bridge

volumes:
  mongodb_data:
